# Generated by Django 5.2.5 on 2025-12-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('CustomerUser', '0001_initial'),
        ('Demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callregister',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company'),
        ),
        migrations.AlterField(
            model_name='callregister',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Demand.demand'),
        ),
        migrations.AlterField(
            model_name='callregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CustomerUser.customeruser'),
        ),
    ]
