# Generated by Django 5.2.5 on 2025-09-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callregister',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
