# Generated by Django 5.2.5 on 2025-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUser', '0002_callregister_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='callregister',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='callregister',
            name='user',
        ),
        migrations.AddField(
            model_name='callregister',
            name='user',
            field=models.ManyToManyField(to='CustomerUser.customeruser'),
        ),
    ]
