# Generated by Django 5.2.5 on 2025-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerUser', '0003_callregister_value_remove_callregister_user_and_more'),
        ('Demand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='value',
        ),
        migrations.AddField(
            model_name='demand',
            name='user',
            field=models.ManyToManyField(to='CustomerUser.customeruser'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
