# Generated by Django 5.2.5 on 2025-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('CustomerUser', '0003_callregister_value_remove_callregister_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(to='CustomerUser.customeruser'),
        ),
    ]
